### ISSUE TITLE
Server - Utilities

### ISSUE THREAD

**Issue by markpollack** [spring-projects-experimental/spring-ai-mcp#18]
- [ ] Pagination - Implement https://spec.modelcontextprotocol.io/specification/server/utilities/pagination/
- [ ] Logging - Implement https://spec.modelcontextprotocol.io/specification/server/utilities/logging/
- [ ] Completion - Implement https://spec.modelcontextprotocol.io/specification/server/utilities/completion/

**Comment by tzolov** [comment]
Part of #12
