### ISSUE TITLE
New line breaks the json format and throwing issue

### ISSUE THREAD

**Issue by bibekditagtech** [spring-projects-experimental/spring-ai-mcp#21]
Hello spring team,

I am having issue with complex user query, for simple query it work well. if i try complex query json break to parse.

`java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (String)"{"query": "SELECT SUM(rnd_hours) as total_rnd_hours
FROM rnds`

I have tried to override McpFunctionCallback and call function to sanitize response. howver work on first call but failed during internal call. I m using mcp-server-mysql https://github.com/designcomputer/mysql_mcp_server. I really dont know issue need to be report here or client . so sorry in advance

**Comment by tzolov** [comment]
Hi @bibekditagtech, 
Maybe [here](https://github.com/spring-projects-experimental/spring-ai-mcp/blob/8b2ce26e8a1f37a5abbed3f7faa01b75ac7b9518/spring-ai-mcp-core/src/main/java/org/springframework/ai/mcp/client/stdio/StdioServerTransport.java#L227) we can try to remove any new lines or other special characters returned from the tool call. 
The [STDIO](https://spec.modelcontextprotocol.io/specification/basic/transports/#stdio) transport spec: "Messages are delimited by newlines, and MUST NOT contain embedded newlines."

**Comment by bibekditagtech** [comment]
> @bibekditagtech this PR (#22 ) escapes the new line characters before sending it to the server's stdin. However the mcp server would likely have to un-escape those.
> 
> This seems a general limitation of the stdio transport. The sse transport won't have such problems.

@tzolov when will this be release. I am using             <version>0.2.0-SNAPSHOT</version> which contain old code.

**Comment by tzolov** [comment]
@bibekditagtech, the 0.2.0-SNAPSHOT already contains line [escaping functionality](https://github.com/spring-projects-experimental/spring-ai-mcp/blob/main/spring-ai-mcp-core/src/main/java/org/springframework/ai/mcp/client/stdio/StdioClientTransport.java#L294). However, this represents the limit of what an MCP client can do - the server must be capable of handling the escaped content.
As an alternative, you can use the remote (HTTP/SSE) transport if your server supports it. This transport method doesn't experience the line escaping issue.
