### ISSUE TITLE
Failure parsing schema for Jetbrains MCP Server

### ISSUE THREAD

**Issue by cpage-pivotal** [spring-projects-experimental/spring-ai-mcp#30]
**Bug description**
Jetbrains MCP server works with Claude Desktop, but running queries with spring-ai-mcp fails with a schema parsing issue
```
org.springframework.ai.retry.NonTransientAiException: 400 - {
  "error": {
    "message": "Invalid schema for function 'get_open_in_editor_file_path': In context=(), object schema missing properties.",
    "type": "invalid_request_error",
    "param": "tools[1].function.parameters",
    "code": "invalid_function_parameters"
  }
}
```

**Environment**
Spring AI 1.0.0-M4
Spring AI-MCP 0.1.0
Jetbrains MCP Server IDE Plugin 1.0.9

**Steps to reproduce**
Install the Jetbrains Plugin (https://plugins.jetbrains.com/plugin/26071-mcp-server)

Configure MCP Client
```    
    public McpSyncClient mcpClient() {

        var stdioParams = ServerParameters.builder("npx")
                .args("-y", "@jetbrains/mcp-proxy")
                .build();

        var mcpClient = McpClient.sync(new StdioServerTransport(stdioParams));
        var init = mcpClient.initialize();
        return mcpClient;
    }
```
Issue chatclient query that requires use of the Jetbrains tool.

**Expected behavior**
Chatclient call should return successful results, as with Claude Desktop.

**Minimal Complete Reproducible example**
https://github.com/cpage-pivotal/spring-ai-examples/tree/intellij/model-context-protocol/jetbrains

**Comment by tzolov** [comment]
@cpage-pivotal , thanks for raising this issue. 
Apparently it is an interesting schema interoperability issue. If you run this code against the Anthropic Chat Model it works fine. Which explains why the Anthropic Desktop works. 
But the OpenAI API can not handle an the empty schema defined  like `Map("type" : "object")` use by some parameterless tools such as `get_open_in_editor_file_path`:
<img width="692" alt="Screenshot 2024-12-20 at 11 31 49" src="https://github.com/user-attachments/assets/9e7fcdbf-c670-4813-9138-9a016f14b3d2" />

If we replace the `Map("type" : "object")` with an empty map (`Map.of()`) like this:
```java
    @Bean
    public List<McpFunctionCallback> functionCallbacks(McpSyncClient mcpClient) {

        var callbacks = mcpClient.listTools(null)
                .tools()
                .stream()
                .map(tool-> {
                    if (tool.inputSchema().size() == 1 && tool.inputSchema().entrySet().iterator().next().getValue().equals("object")) {
                        return new McpSchema.Tool(tool.name(), tool.description(), Map.of());
                    }
                    return tool;
                })
                .map(tool -> new McpFunctionCallback(mcpClient, tool))
                .toList();
        return callbacks;
    }
```

then the OpenAI works but Anthropic will fail :(

I will raise an issue on the Spring AI project to see if we can handle this internally by model types.

**Comment by tzolov** [comment]
This hack seems to make it work with OpenAI, Anthropic and hopefully with the other models:
```java
        var callbacks = mcpClient.listTools(null)
                .tools()
                .stream()
                .map(tool -> {
                    if (tool.inputSchema().size() == 1
                            && tool.inputSchema().entrySet().iterator().next().getValue().equals("object")) {
                        Map<String, Object> emptySchema = Map.of("type", "object",
                                "properties", Map.of("dummy", Map.of("type", "string")));
                        return new McpSchema.Tool(tool.name(), tool.description(), emptySchema);
                    }
                    return tool;
                })
                .map(tool -> new McpFunctionCallback(mcpClient, tool))
                .toList();

```

**Comment by tzolov** [comment]
@cpage-pivotal can we close this issue with the suggested [workaround](https://github.com/spring-projects-experimental/spring-ai-mcp/issues/30#issuecomment-2556863794)?

**Comment by cpage-pivotal** [comment]
Yes, it works for me!
